debug: false
logging:
  level:
     org.hibernate: ERROR
     org.springframework.web.client: DEBUG
spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    generate-ddl: true
    hibernate:
      naming:
        physical_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
  datasource:
    url: jdbc:mariadb://openncp-db:3306/ehealth_properties?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: openncp
    password: openncp1234
    driver-class-name: org.mariadb.jdbc.Driver
openncp:
  property-file:
    path: ${OPENNCP_PROPERTIES_FILE}