debug: false
spring:
  datasource:
    url: jdbc:mariadb://openncp-db:3306/ehealth_ltrdb?useSSL=false&useUnicode=true&amp;characterEncoding=UTF-8&amp;useFastDateParsing=false
    username: openncp
    password: openncp1234
    driver-class-name: org.mariadb.jdbc.Driver
openncp:
  root:
    path: ${EPSOS_PROPS_PATH}