<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
                  xmlns:q1="http://schemas.message.com/Message"
                  xmlns:q2="http://schemas.message.com/Message"
                  xmlns:sp="https://schemas.xmlsoap.org/ws/2005/07/securitypolicy/"
                  xmlns:tns="https://ehdsi.eu/"
                  xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy"
                  xmlns:wsaw="https://www.w3.org/2007/05/addressing/metadata/"
                  xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
                  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                  targetNamespace="https://ehdsi.eu/"
                  name="SecurityTokenService">
    <wsdl:types>
        <xsd:schema targetNamespace="https://ehdsi.eu/Imports">
            <xsd:import schemaLocation="SecurityTokenService.xsd" namespace="http://schemas.message.com/Message"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="securityTokenRequest">
        <wsdl:part name="rstMessage" type="q1:MessageBody"/>
    </wsdl:message>

    <wsdl:message name="securityTokenResponse">
        <wsdl:part name="IssueTokenResult" type="q2:MessageBody"/>
    </wsdl:message>
    <wsdl:portType name="SecurityTokenServicePortType">
        <wsdl:operation name="issueTreatmentToken">
            <wsdl:input message="tns:securityTokenRequest" wsaw:Action="urn:ehdsi:sts:issueTreatmentTokenRequest"/>
            <wsdl:output message="tns:securityTokenResponse" wsaw:Action="urn:ehdsi:sts:issueTreatmentTokenResponse"/>
        </wsdl:operation>
        <wsdl:operation name="issueNextOfKinToken">
            <wsdl:input message="tns:securityTokenRequest" wsaw:Action="urn:ehdsi:sts:issueNextOfKinTokenRequest"/>
            <wsdl:output message="tns:securityTokenResponse" wsaw:Action="urn:ehdsi:sts:issueNextOfKinTokenResponse"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="SecurityTokenServicePortBinding" type="tns:SecurityTokenServicePortType">
        <soap12:binding transport="http://schemas.xmlsoap.org/soap/http" style="document" />
        <wsdl:operation name="issueTreatmentToken">
            <wsp:PolicyReference URI="#SecurityTokenServicePolicy" />
            <soap12:operation soapAction="urn:ehdsi:sts:issueTreatmentTokenRequest" />
            <wsdl:input>
                <soap12:body use="literal" />
            </wsdl:input>
            <wsdl:output>
                <soap12:body use="literal" />
            </wsdl:output>
        </wsdl:operation>
        <wsdl:operation name="issueNextOfKinToken">
<!--            <wsp:PolicyReference URI="#SecurityTokenServicePolicy" />-->
            <soap12:operation soapAction="urn:ehdsi:sts:issueNextOfKinTokenRequest" />
            <wsdl:input>
                <soap12:body use="literal" />
            </wsdl:input>
            <wsdl:output>
                <soap12:body use="literal" />
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="SecurityTokenService">
        <wsdl:port name="SecurityTokenServicePort" binding="tns:SecurityTokenServicePortBinding">
            <soap12:address location="https://sts.ehdsi.eu/services/SecurityTokenService.SecurityTokenServiceHttpsSoap12Endpoint/" />
        </wsdl:port>
    </wsdl:service>
    <wsp:Policy wsu:Id="SecurityTokenServicePolicy">
        <wsp:ExactlyOne>
            <wsp:All/>
        </wsp:ExactlyOne>
    </wsp:Policy>
</wsdl:definitions>
